### ISSUE TITLE
Start-SeDriver 

### ISSUE THREAD

**Issue by itfranck** [adamdriscoll/selenium-powershell#101]
I'd like to remove all the `Start-SeXX` functions and instead use 

`Start-SeDriver -Browser `

This will make maintaining the functions easier as they will still have a common endpoint with a common set of features.
Internal functions to each browser might still be used to separate concerns properly.

To provides additional browser options not common to all, potentially, I see a 

`Get-SeDriverOptions` that would return a hashtable of additional options (eg: So you can easily set the BuiltinPDFreader option exclusive to Chrome, etc)... `

Additionally, I would merge -Minimized / Maximized / FullScreen in a WindowState parameter.

A quick breakdown of the current solution (Start-SeXX)

```

# Currently partially present.
arguments                       2
binarypath                      2
defaultdownloadpath             3
webdriverdirectory              4
hideversionhint                 2
profiledirectorypath            2

#Already everywhere
asdefaultdriver                 5
fullscreen                      5
headless                        5
implicitwait                    5
maximized                       5
minimized                       5
privatebrowsing                 5
quiet                           5
starturl                        5


#Through additional mean (Get-SeDriverOptions?)
disableautomationextension      1
disablebuiltinpdfviewer         1
enablepdfviewer                 1
ignoreprotectedmodesettings     1
suppresslogging                 1
```

**Comment by itfranck** [comment]
Currently working on it. 


```

# Simplest implementation
# Start-SeDriver won't return anything anymore. 
# Last driver started become the selected driver
# Get-SeDriver & Select-SeDriver will allow access to the list of started drivers / change the active one
Start-SeDriver -Browser Chrome -StartURL 'https://www.google.ca' -PrivateBrowsing -DefaultDownloadPath 'SomePath'



# More advanced implementation

#Allow full control over IwebDriverOptions to add anything 
$Options = New-SeDriverOptions -Browser Chrome 

# Provides a selection of "exclusive" switches that might or might not be available depending on the selected browsers.
# Unknown switches are added as regular arguments (eg: $Options.AddArgument)
#Arguments completion take care of adding more complex values (eg: "user-data-dir=$ProfileDirectoryPath")
$Options | Add-SeDriverOptionsArgument -Name 'EnablePDFViewer' -Value $true


Start-SeDriver -Options $Options -State Minimized -StartURL 'https://www.google.ca' 
```

**Comment by vexx32** [comment]
If Start-SeDriver doesn't return anything by default, I think it'd be good to have a `-PassThru` switch to be able to have the created driver returned if needed.

**Comment by itfranck** [comment]
-Passthru was removed and instead the original behavior was kept.
IwebDriver will be returned when calling it.
A default parameter set (#111) ensure that we are not drown into a huge chunk of source code if we were to omit to call this cmdlet outside of a variable / null assignment.

(Ready to be merged in Master once all the other V4 items are completed)
