### ISSUE TITLE
How to get the logs from the Network tab of Chrome DevTools?

### ISSUE THREAD

**Issue by InteXX** [adamdriscoll/selenium-powershell#12]
I'm trying to inspect network traffic as discussed here:

https://stackoverflow.com/a/48636877/722393

Will this be possible using this module?

**Comment by aluitink** [comment]
This module wraps the C# Selenium library. You can do anything you would
otherwise.

**Comment by InteXX** [comment]
That's what I thought, thanks for the confirmation.

I'm trying to work out the syntax now. It's slow going with many errors, but there's a small light at the end of the tunnel.

**Comment by InteXX** [comment]
It seems the assembly doesn't include the `LoggingPreferences` type (documented [here](https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/logging/LoggingPreferences.html)).

This code returns only error entries, with no apparent way to control the output level:

    $Driver = Start-SeChrome
    Enter-SeUrl http://example.com -Driver $Driver
    $Logs = New-Object "OpenQA.Selenium.Remote.RemoteLogs" -ArgumentList $Driver
    $Logs.GetLog([OpenQA.Selenium.LogType]::Browser)

    Timestamp            Level  Message
    ---------            -----  -------
    2/25/2019 5:05:05 PM Severe http://example.com/favicon.ico - Failed to load resource: the server responded with a status of 404 (Not Found)

So I may have to use Java.

I really (REALLY) didn't want to do that...

**Comment by aluitink** [comment]
Have you tried the property on the RemoteLogs object called
"AvailableLogTypes"?

GetLog takes a string, it looks like the LogType Enumerable must have some
common types (maybe cross browser), but the AvailableLogType collection
should be the available log types reported by the chrome driver.

https://github.com/SeleniumHQ/selenium/blob/1156fbc60277cb0a241809c022221541e118ab28/dotnet/src/webdriver/Remote/RemoteLogs.cs

**Comment by InteXX** [comment]
That one returns this:

    browser
    driver

Not much to work with here, it looks like...

Here's a better explanation of what I'm trying to do:

https://stackoverflow.com/q/54875769/722393

I believe I may have hit upon the solution.

I'm pretty sure I'll be able to inject the necessary JavaScript into the page and get the URLs that way.

I tested this Chrome add-in and it captures the info I need:

https://chrome.google.com/webstore/detail/network-record/ihbkogfblhfbnompooimhejpkidoipcl

...and I was able to view its source code with this:

https://chrome.google.com/webstore/detail/chrome-extension-source-v/jifpbeccnghkjeaalbbjmodiffmgedin

I'll know in a couple of days whether this works, and I'll report back here.

**Comment by InteXX** [comment]
@aluitink ~ I got lucky. In the end, it turned out that it wasn't necessary to access Chrome DevTools at all—I was able to get the URLs I needed using this: `JavaScriptExecutor.ExecuteScript("return document.body.innerHTML")`.

**Comment by davidpohanka** [comment]
> ```
> JavaScriptExecutor.ExecuteScript("return document.body.innerHTML")
> ```

Hi @InteXX, could you write me more details about your solution? I'm looking for something similar.

**Comment by InteXX** [comment]
@davidpohanka 

This might help:

https://www.guru99.com/execute-javascript-selenium-webdriver.html
