### ISSUE TITLE
Headless in Chrome not working

### ISSUE THREAD

**Issue by BernieWG** [adamdriscoll/selenium-powershell#120]
My PowerShell script navigates through login, navigation links and a button to download a file.  Interactively the script functions successfully and I get the downloaded file.  Using the -Headless option, it fails on clicking the download button.  What do I need to correct this?
Thank You. 

Chrome:
Google Chrome is up to date
Version 84.0.4147.125 (Official Build) (64-bit)

 ChromeDriver -v
ChromeDriver 84.0.4147.30 (48b3e868b4cc0aa7e8149519690b6f6949e110a8-refs/branch-heads/4147@{#310})

 Start Chrome:
        $Driver = Start-SeChrome -StartURL $StartURL `
            -DefaultDownloadPath $DownloadPath -Quiet -HideVersionHint `
            -DisableAutomationExtension -ImplicitWait 10 –Headless

 Locate and Click Element:
            $LnkExport           = "//*[@id='content']/div/div/datagrid-dynamic/div/div/div/div[3]/div/button[2]/span"
            $ElementXPath    = $LnkExport
            $Element              = Find-SeElement -Driver $Driver -XPath $ElementXPath -Wait 8
            if ($Element)
            {
                try
                {
                    Send-SeClick -Driver $Driver -Element $Element
                }
                catch
                {
                    Write-Host -f Red "Failed to click the Export Icon ... $_.Exception.Message"
                }
            }
            else
            {
                Write-Host -f yellow "Did not locate the export button" $Element
            }

 From Write-Host:

Failed to click the Export Icon ... Exception calling "Click" with "0" argument(s): "element not interactable
  (Session info: headless chrome=84.0.4147.105)".Exception.Message

 

PS Transcript:
**********************
Windows PowerShell transcript start
Start time: 20200817102212
Username: domain\userid
RunAs User: domain\userid
Configuration Name:
Machine: xyz123abc (Microsoft Windows NT 10.0.17763.0)
Host Application: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command Import-Module 'c:\ domain\userid\.vscode\extensions\ms-vscode.powershell-2020.6.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.6.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\ domain\userid\.vscode\extensions\ms-vscode.powershell-2020.6.0\modules' -EnableConsoleRepl -StartupBanner "=====> PowerShell Integrated Console v2020.6.0 <=====
" -LogLevel 'Normal' -LogPath 'c:\ domain\userid\.vscode\extensions\ms-vscode.powershell-2020.6.0\logs\1597677670-235eacdd-efb3-4d55-8a01-3aa8ef642f591597675673236\EditorServices.log' -SessionDetailsPath 'c:\ domain\userid\.vscode\extensions\ms-vscode.powershell-2020.6.0\sessions\PSES-VSCode-20280-127014' -FeatureFlags @()
Process ID: 19268
PSVersion: 5.1.17763.1007
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.17763.1007
BuildVersion: 10.0.17763.1007
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
PS C:\Users\userid\Documents\VSCode\Asset Refresh> TerminatingError(Send-SeClick): "Exception calling "Click" with "0" argument(s): "element not interactable
  (Session info: headless chrome=84.0.4147.105)""
Failed to click the Export Icon ... Exception calling "Click" with "0" argument(s): "element not interactable
  (Session info: headless chrome=84.0.4147.105)".Exception.Message
**********************
Windows PowerShell transcript end
End time: 20200817102359
**********************

**Comment by itfranck** [comment]
@BernieWG 

Can you try adding  `-Arguments "window-size=1920,1080"` to your `Start-SeChrome` statement ?


```
$Params = @{
  StartURL = $StartURL 
  DefaultDownloadPath = $DownloadPath
  Quiet = $true 
  HideVersionHint = $true 
  DisableAutomationExtension = $true
  ImplicitWait = 10 
  Headless = $true
}

$Driver = Start-SeChrome @Params -Arguments "window-size=1920,1080"
```

Let me know if it work for you.

If it doesn't, I think you need to look at the `$Element` variable just before calling `Send-SeClick`

Change the 

```
try
{
Send-SeClick -Driver $Driver -Element $Element
}
```

for 
```
try {
  $Element 
  Get-SeElementAttribute -Element $Element -attribute 'outerHTML' 
  Send-SeClick -Driver $Driver -Element $Element
}
```

Try it both with the headless browser and the regular one. 



My guess is that something will be different between the two execution.
Either the element will be marked as hidden (displayed = false), it's location and / or / size will be something funky (no size, location at 0/0) 

That's why setting an explicit size to the headless browser might resolve the situation.
(although this is a shot in the dark) 

If your problem is not resolved at this point and the previous points does not apply, including the text output of `$Element` might help in identifying the problem. 
 
Output should be similar to this one. 
![image](https://user-images.githubusercontent.com/1980296/90463061-0e8e8380-e0d8-11ea-8d79-108bccd5e8dd.png)

**Comment by itfranck** [comment]
Closing this. If the answer provided do not work for you, please reopen this ticket along with the requested information and we can look further into it. Thanks.
