### ISSUE TITLE
Mouse actions or sending keystrokes

### ISSUE THREAD

**Issue by be1t1s** [adamdriscoll/selenium-powershell#128]
Are there any plans or a way to either send a ${KEY_UP} / {KEY_DOWN} or a mouse up / mouse down action?

**Comment by itfranck** [comment]
Hi @be1t1s , I am currently actively working on a V4 of the module which will include additional support for Selenium actions. 

That does include support for all the actions described [here](https://www.selenium.dev/selenium/docs/api/dotnet/html/Methods_T_OpenQA_Selenium_Interactions_Actions.htm) including the one you mentionned

See #122  (Support for [OpenQA.Selenium.Interactions.Actions] (Double-click / Drag & Drop, etc...) And TouchActions ) for the request that encompass this one. 

V4 is something that is planned for October but if you have a need for it now, you can look at the example I provided on #72 for applying an action (This was for a MouseMove but you can change the action for any of the other available actions)
