### ISSUE TITLE
Explicit Wait not working...

### ISSUE THREAD

**Issue by onenessboy** [adamdriscoll/selenium-powershell#130]
I am loading urls from text file one by one.
but after each url load, i need to ask program to wait for 10 second before opening next url... I tried below but its not waiting..for 10 second

```
$Driver = Start-SeChrome -Maximized

$urls= gc "C:\CSV\aburl.txt"
foreach ($url in $urls){
    #Write-Host "Url is: $url"	
	Enter-SeUrl $url -Driver $Driver}
	Start-Sleep -Seconds 10

Stop-SeDriver -Driver $Driver
```

How can i overcome this issue ? any ideas please..

**Comment by vexx32** [comment]
Your Start-Sleep is outside of your loop, it ends after the Enter-SeUrl line.

I'd recommend keeping closing braces on the beginning of the next line, it helps make scopes much more clear 🙂 

```ps1
$Driver = Start-SeChrome -Maximized

$urlList= Get-Content -Path "C:\CSV\aburl.txt"
foreach ($url in $urlList) {
    #Write-Host "Url is: $url"
    Enter-SeUrl $url -Driver $Driver
    Start-Sleep -Seconds 10
}

Stop-SeDriver -Driver $Driver

**Comment by onenessboy** [comment]
> ```powershell
> $Driver = Start-SeChrome -Maximized
> 
> $urlList= Get-Content -Path "C:\CSV\aburl.txt"
> foreach ($url in $urlList) {
>     #Write-Host "Url is: $url"
>     Enter-SeUrl $url -Driver $Driver
>     Start-Sleep -Seconds 10
> }
> 
> Stop-SeDriver -Driver $Driver
> ```

Yo Yo. It works... sorry for that silly mistake...
