### ISSUE TITLE
IE driver issue.

### ISSUE THREAD

**Issue by onenessboy** [adamdriscoll/selenium-powershell#131]
I am trying this

```
$Driver = Start-SeInternetExplorer -Maximized

````

I get below error:

```
Exception calling ".ctor" with "2" argument(s): "Unexpected error launching Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all
zones. (SessionNotCreated)"
At C:\Program Files\WindowsPowerShell\Modules\Selenium\3.0.1\Selenium.psm1:321 char:5
+     $Driver = [OpenQA.Selenium.IE.InternetExplorerDriver]::new($servi ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidOperationException
```

**Comment by vexx32** [comment]
You'll need to configure the zones in IE or the Windows system settings before using it, I'd imagine. Similar issue turns up if you `Invoke-WebRequest` in powershell without `-UseBasicParsing` before running IE at least once and setting some things up.

Not much this module can do, that's purely an IE issue.

**Comment by itfranck** [comment]
As per above comment, you need to set the security zones all the same. 

1. Open IE
2. Go to Tools -> Internet Options -> Security
3. Set all zones (Internet, Local intranet, Trusted sites, Restricted sites) to the same protected mode, enabled or disabled should not matter.

This restriction comes from Selenium 

For more information on why it is the case, check this out: http://jimevansmusic.blogspot.co.uk/2012/08/youre-doing-it-wrong-protected-mode-and.html
