### ISSUE TITLE
Start-SeChrome in headless mode doesnt work.

### ISSUE THREAD

**Issue by the-mentor** [adamdriscoll/selenium-powershell#14]
Dear Dev,
First thank you for all your hard work this module is amazing!!

When i try to start chrome in headless mode it doesn't work and still opens the chrome window i'm using the following command.
$Driver = Start-SeChrome -Arguments "headless"

I'm using version 1.1 of the module.
Also i noticed that the Start-SeChrome doesn't have the Arguments parameter i'm not sure if that is the issue.

Thanks.
-DM

**Comment by the-mentor** [comment]
After some further investigation it looks like this github has the required code to run chrome as headless but the module in the powershell gallery wasn't updated to reflect this update.

Thanks.
-DM

**Comment by mavericksevmont** [comment]
Just noticed that too, same issue, same fix

**Comment by adamdriscoll** [comment]
I've published the new version of the module to the gallery
