### ISSUE TITLE
[V4.0] Scoping issue with Pester test / Script validation

### ISSUE THREAD

**Issue by itfranck** [adamdriscoll/selenium-powershell#142]
Combined testing now fails when relying upon argument completer / Script variable stating the validation failed.
Validation is failing because the `$Script` scope is not populated.

```
Get-SeElement      $linkXPath | Invoke-SeClick  -Action Click_JS -SleepSeconds 1
```

I found this issue after modifying that specific cmdlet but it will equally fail with the new cmdlet.

**Comment by itfranck** [comment]
It looks like the issue comes from how Pester work internally. 
I really do not understand. 
The function get declared properly but the `$script:` variables used by those functions are empty yet declared in the same file. 
This make no sense at all. 

The workaround that I will likely implement is to wrap the scirpt variable into functions and replace all variable checks by function call. Still checking though as I find this solution really disappointing.

**Comment by vexx32** [comment]
Is this in v5 of Pester, or does this also show up in v4?

**Comment by itfranck** [comment]
@vexx32 
This occurs in both. 

It looks like this affect the scripts to process from the manifest 
```
ScriptsToProcess     = @('SeleniumClasses.ps1')
```

All the `$Script` variables from that file are empty when called from Pester. 
The functions that uses these variables are also declared in the SeleniumClasses.ps1. 

- I found that if I move the functions and the `$Script` variables into the Root module itself, then it work properly.
- Importing / using the module normally do not produce that behavior. 
- Using the Code lens "Run test" button from within vscode do not produce this behavior. 


Using the following way to start the test do produce the behavior. 

From debug.ps1
```
#From debug.ps1
. $ProjectPath\CI\CI.ps1 -browserlist Chrome #, Firefox
```
Which call

```
Import-Module "$ModulePath/$($ModulePathSuffix)Selenium.psd1" -Force -ErrorAction Stop
...
& "$PSScriptRoot\Pester-To-XLSx.ps1"  @RunParameters
```
Which finally call 
```
 Invoke-Pester @InvokePesterParams  -ErrorAction Continue 
```

There's no reason I can think of for all the `$Script` variables to be empty in `SeleniumClasses` when a function from that same file query one of these variables. Since this work in other scenarios (normal import / Run Test from code lens), I think that this might be a real bug with Pester (although an edge case).

As for how I will address it, simply moving the relevant functions / variables in the root module do the trick since I don't need these to be loaded before the root module so I will do that. 

I'll try to isolate & reproduce the issue in an empty project.
If I am successful, I'll open a bug on the Pester project directly.
