### ISSUE TITLE
Using unattended fails due to timeout?

### ISSUE THREAD

**Issue by janiklingberg** [adamdriscoll/selenium-powershell#15]
I have a small bit of Powershell Selenium code set up as a Scheduled Task that would run every night. This worked fine for many months, however now it's failing consistently with timeout errors:

> Exception calling "GoToUrl" with "1" argument(s): "The HTTP request to the remote WebDriver server for URL http://localhost:60320/session/efdcda192ce74a161bf80dcf5e31b9f4/url timed out after 60 seconds."

How can I increase the timeout value? I've tried

```
$new_timespan = new-timespan -minute 3
$driver.Manage().Timeouts().PageLoad = $new_timespan
```

after initializing $driver but that didn't seem to do the trick...

**Comment by mavericksevmont** [comment]
Try either one of the following:

```
$Driver.Manage().Timeouts().Pageload = [TimeSpan]::FromSeconds(180)
$Driver.Manage().Timeouts().Pageload = [TimeSpan]::FromMinutes(3)
```
How that helps :)

**Comment by adamdriscoll** [comment]
Another cool place to have a cmdlet. 

Set-SeDriver -Driver $Driver -PageLoadTimeout ([TimeSpan]::FromSeconds(180))

**Comment by the-mentor** [comment]
@janiklingberg  are you still having this issue?

-DM
