### ISSUE TITLE
Can I send keys (Enter, Return, Arrows and others) with Send-SeKeys 

### ISSUE THREAD

**Issue by svdudnak** [adamdriscoll/selenium-powershell#16]
Unfortunately, no way to use KEYS.ENTER or Keys.RETURN
Using key-codes - u'\ue006' or u'\ue007' - not working too.

**Comment by mavericksevmont** [comment]
Hi, I've been calling the methods directly from $Driver instead of using the cmdlet, e.g.:

```
$Driver.FindElementByName('YourObject').SendKeys([OpenQA.Selenium.Keys]::Enter)
$Driver.FindElementByName('YourObject').SendKeys([OpenQA.Selenium.Keys]::Return)
```

Hope that helps!

**Comment by svdudnak** [comment]
Great ! Thats really works, man ! Tnx very much.
