### ISSUE TITLE
'acceptInsecureCerts' Argument for Start-SeFirefox?

### ISSUE THREAD

**Issue by aescolastico** [adamdriscoll/selenium-powershell#189]
Is this an available option?

**Comment by itfranck** [comment]
@aescolastico 

As far as I know, it is not possible with V3.
V4 do not support that with a simple switch but is much more flexible when it comes to access stuff under the hood. 

In V4, you'd start the browser in the following manner: 
```
Start-SeDriver -Browser Firefox -StartURL 'https://self-signed.badssl.com/'
```

At that point though, you would get the certificate error. 
To go around that and by looking at Selenium Firefox documentation, you can bypass insecure certificate warning by adding a capability to your driver options. V4 do have a function `New-SeDriverOptions` to expose it. 
From there, you can modify the option accordingly and start the browser.

Here is the relevant code. 

```
$Options = New-SeDriverOptions -Browser Firefox
$Options.AddAdditionalCapability([OpenQA.Selenium.Remote.CapabilityType]::AcceptInsecureCertificates, $true,$true)
$Options.ToCapabilities()
Start-SeDriver -Browser Firefox -Options $Options -StartURL 'https://self-signed.badssl.com/'
```

Note that while testing this, I found an issue that will prevent this from working in V4.0-preview1.
It is fixed for Preview2 and will work properly.

V4 is a major rewrite from V3 though and if you had working V3 scripts, there will definitely be rework to make them V4 compliant.

**Comment by itfranck** [comment]
I'll keep this issue open until V4.0.0-Preview2 is released

**Comment by itfranck** [comment]
It looks like at least Chrome support that too. 
Therefore, I'll add a switch so you can do : 

```
Start-SeDriver -Browser Firefox -StartURL 'https://self-signed.badssl.com/' -AcceptInsecureCertificates
```

The `New-SeDriverOptions` is still useful for anything not implemented directly but in this case, it make sense to add it in the Start-SeDriver switches.

**Comment by itfranck** [comment]
Done. 

In v4.0-preview2, you'll be able to use : 

```
Start-SeDriver -Browser Edge -StartURL 'https://self-signed.badssl.com/' -AcceptInsecureCertificates
```

I'll publish a release by Dec. 7th end of day.
