### ISSUE TITLE
Unable to type in URL and Try to login 

### ISSUE THREAD

**Issue by mahi2pavuluri** [adamdriscoll/selenium-powershell#2]
New-Object : Exception calling ".ctor" with "0" argument(s): "The HTTP request to the remote WebDriver server for URL 
http://localhost:58807/session timed out after 60 seconds."
At C:\Program Files\WindowsPowerShell\Modules\Selenium\1.0\Selenium.psm1:18 char:19
+ ...   $Driver = New-Object -TypeName "OpenQA.Selenium.Firefox.FirefoxDriv ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand

**Comment by chris-simpkins** [comment]
I have this same issue when trying to run the script as a non-administrator, do you still encounter this issue when running in an elevated session?

**Comment by the-mentor** [comment]
@mahi2pavuluri @chris-simpkins are you still having these issues with the latest version of the module?

**Comment by BenjaminBaxleyINAP** [comment]
To prevent the page from throwing a timeout error and just move on to the next command even if the page isn't fully loaded, try running the driver with these options:

$ChromeOptions = [OpenQA.Selenium.Chrome.ChromeOptions]::new()
$ChromeOptions.PageLoadStrategy = "None"
$driver = New-Object -TypeName "OpenQA.Selenium.Chrome.ChromeDriver" -ArgumentList @($ChromeOptions)

**Comment by the-mentor** [comment]
No response from @mahi2pavuluri 
Issue Closed.

-DM
