### ISSUE TITLE
Example in Help for New-SeScreenshot is wrong (probably outdated)

### ISSUE THREAD

**Issue by ZonderP** [adamdriscoll/selenium-powershell#200]
e.g.: 'Get-Help New-SeScreenshot -Example' gives:

  
    -------------------------- Example 1 --------------------------
    
    PS C:\> New-SeScreenshot -Path 'c:\temp\Screenshot.png' -ImageFormat Png
    
    Save a screenshot in PNG format at the specified location

This is with v4.0.0-preview2 and seems to be a remnant from an older version.

**Comment by itfranck** [comment]
I will publish Preview3 today that will include this change.
