### ISSUE TITLE
Ignore Zoom Level For Internet Explorer / Edge

### ISSUE THREAD

**Issue by billkindle** [adamdriscoll/selenium-powershell#23]
The closest explanation I can find is here:

[https://stackoverflow.com/questions/12034969/internetexplorerdriver-zoom-level-error](https://stackoverflow.com/questions/12034969/internetexplorerdriver-zoom-level-error)

I'm seeing the same thing. I've attached a screenshot of the error below.
<img width="432" alt="Selenium_Error" src="https://user-images.githubusercontent.com/7315466/62411891-2e83ff80-b5c8-11e9-8382-998be7436ca2.png">

**Comment by adamdriscoll** [comment]
Resolved in #31
