### ISSUE TITLE
Start-SeChrome multiple Arguments does not work

### ISSUE THREAD

**Issue by rommel-baltazar** [adamdriscoll/selenium-powershell#24]
Thanks for your amazing module. I'm trying to invoke Start-SeChrome with multiple arguments (array) but getting an unexpected output (second argument opens as a tab in the browser).

i.e.  $Driver = Start-SeChrome -Arguments  "start-maximized","incognito"

will do:

![image](https://user-images.githubusercontent.com/9526129/62424603-449ed680-b714-11e9-9aba-891b5560277e.png)

**Comment by the-mentor** [comment]
Hi @rommel-baltazar,
I've added -Maximized and -Incognito to Start-SeChrome
It should be in GitHub soon.
Once its merged you can give it a spin and let me know if it works for you.

**Comment by adamdriscoll** [comment]
Resolved in #31

**Comment by rommel-baltazar** [comment]
> Hi @rommel-baltazar,
> I've added -Maximized and -Incognito to Start-SeChrome
> It should be in GitHub soon.
> Once its merged you can give it a spin and let me know if it works for you.

Thanks @the-mentor , it's working fine.
