### ISSUE TITLE
By CssSelector

### ISSUE THREAD

**Issue by pHiney** [adamdriscoll/selenium-powershell#3]
$Driver.FindElements([OpenQA.Selenium.By]::CssSelector('#loginBox input[value="Login"]')) 

works.

Do you want to update Find-SeElement ?

Peter

**Comment by adamdriscoll** [comment]
Yes. That would great!

**Comment by vitalics** [comment]
@adamdriscoll, @pHiney PR #19 is waiting for review

**Comment by adamdriscoll** [comment]
Merged!
