### ISSUE TITLE
Possible to run inside a Job?

### ISSUE THREAD

**Issue by wicked1133** [adamdriscoll/selenium-powershell#34]
I have tried a simple test and want to run paralelle within Jobs. But somehow the Job just completes and doesnt run the script to the end.

Is it even possible to run inside a Job? 

This is the simple testscript I am using:
```
Start-Job -Name test -ScriptBlock {
  $Driver = Start-SeChrome
  Enter-SeUrl https://google.com -Driver $Driver

  if (Find-SeElement -Driver $Driver -ClassName "gLFyf") {
      Write-Verbose -Message "Test successfull" -Verbose
  } else {
      Write-Verbose -Message "Test Error" -Verbose
  }
  #Stop-SeDriver $Driver
}

**Comment by mavericksevmont** [comment]
Hi, something similar happens to me with other modules, since it's a separate runspace you might have to load/import the module again within the job's scriptblock. have you used a try/catch for the import-module and/or related cmdlets?

**Comment by itfranck** [comment]
The Se prompt output will be disabled by default in V4. 
For now, the workaround above should do the trick.

If you find other cases where it fails to work within jobs with the `-quiet` parameter, feel free to open a new ticket and I will take a look at it.
