### ISSUE TITLE
Any method to specify binary location for Chrome?

### ISSUE THREAD

**Issue by sethjbr** [adamdriscoll/selenium-powershell#39]
I know the README says that the browser has to be installed, but in most implementations of selenium, there is an option to specify the binary location for where chrome.exe is located so that Google Chrome doesn't have to be installed on the system.

Is that possible?

Thanks.

**Comment by the-mentor** [comment]
@sethjbr it doesn't exist at the moment but I've created a PR to add this functionality.

[Link to PR ](https://github.com/adamdriscoll/selenium-powershell/pull/42)

Check it out.

-DM

**Comment by adamdriscoll** [comment]
Merged!
