### ISSUE TITLE
how to switch to frame 0 in the document model.

### ISSUE THREAD

**Issue by billhsabillhsa** [adamdriscoll/selenium-powershell#40]
Hi, 
Below at very bottom is the java script generated by selenium ide. I use the following three lines but can't find the element called username as I don't know how to switch to frame 0 in the document model.

$Driver = Start-SeChrome
Enter-SeUrl https://www.xyz.com/ -Driver $Driver
$Element = Find-SeElement -Driver $Driver -Id "username"

What is the powershell commands for the following two lines?

driver.manage().window().setSize(new Dimension(1920, 1040));
    driver.switchTo().frame(0);

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class Test12Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test12() {
    driver.get("https://sez00vvm-500.sweng.ncr.com/vsphere-client/?csp");
    driver.manage().window().setSize(new Dimension(1920, 1040));
    driver.switchTo().frame(0);
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("test");
    driver.findElement(By.id("password")).sendKeys("test1");
    driver.findElement(By.id("submit")).click();
  }
}

**Comment by masterpipo** [comment]
Encountering this as well.

I see Switch-SEFrame on https://github.com/adamdriscoll/selenium-powershell/blob/master/Selenium.psm1#L1039, but I can't seem to call this as a commandlet or function

**Comment by masterpipo** [comment]
> Hi,
> Below at very bottom is the java script generated by selenium ide. I use the following three lines but can't find the element called username as I don't know how to switch to frame 0 in the document model.
> 
> $Driver = Start-SeChrome
> Enter-SeUrl https://www.xyz.com/ -Driver $Driver
> $Element = Find-SeElement -Driver $Driver -Id "username"
> 
> What is the powershell commands for the following two lines?
> 
> driver.manage().window().setSize(new Dimension(1920, 1040));
> driver.switchTo().frame(0);
> 
> // Generated by Selenium IDE
> import org.junit.Test;
> import org.junit.Before;
> import org.junit.After;
> import static org.junit.Assert._; import static org.hamcrest.CoreMatchers.is; import static org.hamcrest.core.IsNot.not; import org.openqa.selenium.By; import org.openqa.selenium.WebDriver; import org.openqa.selenium.firefox.FirefoxDriver; import org.openqa.selenium.chrome.ChromeDriver; import org.openqa.selenium.Dimension; import org.openqa.selenium.WebElement; import org.openqa.selenium.interactions.Actions; import org.openqa.selenium.support.ui.ExpectedConditions; import org.openqa.selenium.support.ui.WebDriverWait; import org.openqa.selenium.JavascriptExecutor; import org.openqa.selenium.Alert; import org.openqa.selenium.Keys; import java.util._;
> public class Test12Test {
> private WebDriver driver;
> private Map<String, Object> vars;
> JavascriptExecutor js;
> @before
> public void setUp() {
> driver = new ChromeDriver();
> js = (JavascriptExecutor) driver;
> vars = new HashMap<String, Object>();
> }
> @after
> public void tearDown() {
> driver.quit();
> }
> @test
> public void test12() {
> driver.get("https://sez00vvm-500.sweng.ncr.com/vsphere-client/?csp");
> driver.manage().window().setSize(new Dimension(1920, 1040));
> driver.switchTo().frame(0);
> driver.findElement(By.id("username")).click();
> driver.findElement(By.id("username")).sendKeys("test");
> driver.findElement(By.id("password")).sendKeys("test1");
> driver.findElement(By.id("submit")).click();
> }
> }

I am able to now switch to Frame 0 by using the following:

> $Driver.SwitchTo().Frame("0")

**Comment by be1t1s** [comment]
Hi everyone,
this is still an issue, anything other than input 0 breaks, any fixes up on the horizon?

**Comment by itfranck** [comment]
@be1t1s 

What is Frame 0 ? 
The root frame or a frame named '0'. 

```
Switch-SeFrame -Root
Switch-SeFrame -Frame '0'
```

One or the other should work. 
Do you have the latest version (3.0.1) ?

Here's another example of `Switch-SeFrame`
```
Start-SeChrome -StartURL $SelectTestPage
Start-Sleep -Seconds 5 # to allow the page to load
Switch-SeFrame  'iframeResult'
Switch-SeFrame -Root
```

If the page is public,  I can take a look at your specific scenario.

**Comment by ili101** [comment]
That issue was probably fixed by https://github.com/adamdriscoll/selenium-powershell/pull/175/commits/beda411a34af8de042db29d6be7e13ce36622512

**Comment by itfranck** [comment]
I believe too this is fixed (I can't attest for V3, but V4 should have no problems).

If not, please provide additional details and I will review this.
