### ISSUE TITLE
How to handle Popup Dialogs?

### ISSUE THREAD

**Issue by darindavis** [adamdriscoll/selenium-powershell#44]
I have a PS script that uses Firefox to download a CSV file from a web site.  The challenge is that when I click the download button, the web site opens a popup dialog box prompting me to open the file or save it.  The way I'm currently handling this is via the AutoIt module.  However, I see in https://www.seleniumhq.org/docs/03_webdriver.jsp that there is a switchTo().alert() function. So, I tried $Driver.SwitchTo().Alert() but got: Exception calling "Alert" with "0" argument(s): "No modal dialog is currently open".  I'm unclear if this is the correct way to handle this modal dialog.

Alternatively, (per https://stackoverflow.com/questions/13839544/using-selenium-webdrivers-method-browser-helperapps-neverask-savetodisk-how-ca) there is a way to set a FireFox profile preference, i.e. profile.setPreference("browser.helperApps.neverAsk.saveToDisk", "text/csv").  Is there a way to do this in the Selenium PS module?

Thanks!

**Comment by Dextroz** [comment]
Hi there, I believe the second option is possible to impliment.

I will draft up a PR.

**Comment by Dextroz** [comment]
Back again :-)

The following example will allow you to download a CSV file without a pop-up window.

````
# Init FirefoxOptions.
$Firefox_Options = New-Object -TypeName "OpenQA.Selenium.Firefox.FirefoxOptions"
# This is the important line. 😄 
$Firefox_Options.SetPreference("browser.helperApps.neverAsk.saveToDisk", "application/octet-stream");
$Driver = New-Object -TypeName "OpenQA.Selenium.Firefox.FirefoxDriver" -ArgumentList $Firefox_Options
Enter-SeUrl -Driver $Driver -Url "https://foobar.com/somecsvfile.csv"
```

**Comment by Dextroz** [comment]
Future reference: The following [StackOverflow post](https://stackoverflow.com/a/34780823) could be useful for removing the pop-up for other file types.

**Comment by darindavis** [comment]
Dextrox - Thanks for the reply.  I tried your code but got:

>  Add-Type -AssemblyName OpenQA.Selenium.Firefox.FirefoxOptions
Add-Type : Cannot add type. The assembly 'OpenQA.Selenium.Firefox.FirefoxOptions' could not be 
found.
>  Add-Type -AssemblyName OpenQA.Selenium.Firefox
Add-Type : Cannot add type. The assembly 'OpenQA.Selenium.Firefox' could not be found.
>  Add-Type -AssemblyName OpenQA.Selenium
Add-Type : Cannot add type. The assembly 'OpenQA.Selenium' could not be found.
>  Add-Type -AssemblyName OpenQA
Add-Type : Cannot add type. The assembly 'OpenQA' could not be found.

I'm sure I'm missing something obvious, but I'm struggling to see it.  Thoughts?

**Comment by Dextroz** [comment]
Sorry, at the top try adding ‘Import-Module -Name “Selenium”

**Comment by the-mentor** [comment]
@darindavis you can specify the DefaultDownloadPath to specify an automatic download folder 
```$Driver = Start-SeFirefox -DefaultDownloadPath 'c:\temp'```

-DM

**Comment by darindavis** [comment]
@the-mentor Thanks for the tip.  From [https://stackoverflow.com/questions/41644381/python-set-firefox-preferences-for-selenium-download-location](https://stackoverflow.com/questions/41644381/python-set-firefox-preferences-for-selenium-download-location) I found the syntax to change the download folder using SetPreference:

```
$Firefox_Options.SetPreference("browser.download.dir", "c:\temp")
$Firefox_Options.SetPreference("browser.download.folderList", 2) # 0 means to download to the desktop, 1 means to download to the default "Downloads" directory, 2 means to use the directory

```
