### ISSUE TITLE
Exception calling "LoadFrom" with "1" argument(s): "Could not load file or assembly ...

### ISSUE THREAD

**Issue by AcerScottLee** [adamdriscoll/selenium-powershell#5]
I executed Selenium.psm1,but it has an error : "Exception calling "LoadFrom" with "1" argument(s): "Could not load file or assembly 'file:///D:\GoogleDrive\IT\Powershell\Selenium-Powershell\assemblies
\WebDriver.dll' or one of its dependencies. The operation is not supported. (Exception from HRESULT: 0x80131515)"
At line:1 char:1"

My PSVersion  is:   5.1.14409.1012
plz give me some advice, Tks

**Comment by AcerScottLee** [comment]
I find the issue it's a NET Version error

**Comment by ukndhak78** [comment]
how to stop PowerShell run autostart  with this massage 
____________________________________________________________


Exception calling "Load" with "1" argument(s): "Could not load file or assembly '2614840 bytes loaded from Anonymously
Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An
attempt was made to load a program with an incorrect format."
At line:1 char:1
+ [System.Reflection.Assembly]::Load([System.Convert]::FromBase64String ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : BadImageFormatException
