### ISSUE TITLE
URL handling

### ISSUE THREAD

**Issue by anotherusername1234** [adamdriscoll/selenium-powershell#54]
when calling start-sechrome with a URL in Format 
"https://portal.xxx.com/WikiTest1/Pages/Technische%20und%20organisatorische%20Maßnahmen%20%28TOMs%29.aspx"
PowerShell returns the error 
Incorrect StartURL please make sure the URL starts with http:// or https://
In C:\Users\xxxxx\Documents\WindowsPowerShell\Modules\Selenium\2.2.0\Selenium.psm1:60 character:17

The error also occurs if I swap out the encoded space characters and with any type of quoting I've been able to figure. 

Selenium Module 2.2.0

PS C:\Users\xxx> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.18362.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by anotherusername1234** [comment]
Looking further at this it seems to be the german character in the URl that causes the error - ß

It's failing on this check - https://docs.microsoft.com/en-us/dotnet/api/system.uri.iswellformeduristring?view=netframework-4.8

**Comment by jmiller76** [comment]
Does it do the same thing with single quotes?

**Comment by anotherusername1234** [comment]
Hi,

yep the same thing. Weirdly in browser the ß (German) character is accepted and fine but from the command line it fails. Other standard ascii characters like brackets, percentage etc are fine.

Thanks




Simon Rowe
IT Infrastructure

Direct +49 69 97130-443
Mobile +49 172 8410957
E-Mail S.Rowe@taylorwessing.com
<mailto:S.Rowe@taylorwessing.com>
Taylor Wessing Partnerschaftsgesellschaft mbB
Thurn-und-Taxis-Platz 6
60313 Frankfurt a.M.

Fax +49 69 97130-100
www.taylorwessing.com

[cid:klein_hohe_Aufl.jpg@561DC24A.0001]<http://iot.taylorwessing.com>

Von: jmiller76 <notifications@github.com>
Gesendet: Freitag, 22. November 2019 20:05
An: adamdriscoll/selenium-powershell <selenium-powershell@noreply.github.com>
Cc: Rowe, Simon <S.Rowe@taylorwessing.com>; Author <author@noreply.github.com>
Betreff: Re: [adamdriscoll/selenium-powershell] URL handling (#54)


Does it do the same thing with single quotes?

**Comment by the-mentor** [comment]
@anotherusername1234 this probably happens due to a URL encoding problem.
I will have to investigate the issue since it might be a PowerShell problem or a driver problem.
Once I have more information i will update this thread.

Thank you for your patience!
-DM

**Comment by the-mentor** [comment]
@anotherusername1234 something seems to be wrong with your URL but its not the letter ß
I just ran the below code without issues.
```$d = Start-SeChrome -StartURL 'https://www.google.com/search?q=testß'```

this is the function that validates the URL
```[system.uri]::IsWellFormedUriString($StartURL,[System.UriKind]::Absolute)```
and it seems to return false to your URL for some reason.
Without access to the real URL I can't preform any further investigation.
If you want you can send me the full URL in a direct message so I can investigate further.

Thank you!
-DM

**Comment by the-mentor** [comment]
This issue is resolved in https://github.com/adamdriscoll/selenium-powershell/pull/56
Please allow a few days for the fix to be released to the PS gallery.

Thank you very much!
-DM
