### ISSUE TITLE
Edge and CrEdge

### ISSUE THREAD

**Issue by jhoneill** [adamdriscoll/selenium-powershell#55]
Have you had any luck getting things working with the New / Chromium version of Edge ? 

`Start-SeChrome -ChromeBinaryPath   "C:\Program Files (x86)\Microsoft\Edge Dev\Application\80.0.334.3\msedge.exe"`
Launches [todays Dev build of] Edge, but  fails with the message
` "The HTTP request to the remote WebDriver server for URL http://localhost:58919/session timed out after 60 seconds."`

I can't find a chromium driver for v80...  So I also tried the earlier beta which is still on 79 
```
>$driver2 = Start-SeChrome -ChromeBinaryPath   "C:\Program Files (x86)\Microsoft\Edge Beta\Application\79.0.309.30\msedge.exe"
Starting ChromeDriver 79.0.3945.36
```
Same error (except for the port number). 
 Microsoft have a webdriver at
 https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/  
but none of the _obvious_ things got that working. I have a strong sense that I am missing something :-) 

The in-box driver for "Old" Edge is 17134 (1803 IIRC)  and that page says run 
`DISM.exe /Online /Add-Capability /CapabilityName:Microsoft.WebDriver~~~~0.0.1.0`
to get the current MicrosoftWebdriver.exe 
It Installs in Windows\system32  from where it can be copied to the assemblies folder and that works just fine. It might be worth including a hint message about edge versions like the one you already have for chrome. (Though how many people actually care about steam-driven edge is another matter). 

[Major tip of the hat for this module, BTW. I last worked on Selenium in 2014 and thought about doing some PS stuff for it, but change of job and priorities, plus the size of the task meant it never went anywhere.]

**Comment by the-mentor** [comment]
Hi @jhoneill we haven't done any work for the new Edge browser based on chromium.
My guess is that you cant just use a regular chrome driver and will need to use a specific driver for chrome.
You can find more information here
https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/
I've tagged this issue as feature request and we will try to add support for it as time allows.

Thank you!
-DM

**Comment by jhoneill** [comment]
Thanks for the response. I suspect that if you need use Edges's own web driver that will need support on the OpenQA side before you can do anything. 
I think that keeping it on the list of feature requests for the future is sensible option for now. 
If a solution presents itself,  I might code it up and send you a PR. 
Thanks again
J

**Comment by the-mentor** [comment]
I wonder what will be a good command for the new Chromium based Edge 
Start-SeEdgeium  ? 

@adamdriscoll what do you think?

-DM

**Comment by jhoneill** [comment]
I think you've had a defacto convention that if the driver name is [openqa.....ABCdriver] then the command is Start-SeABC  , if it needs support for the extra type of web driver to go into the library then I'd follow that. 
Opera and Safari drivers are also present in the library and it would make sense to add those at some point, although you'd need those browsers/drivers installed to test them
The exes are named "MicrosoftWebDriver" for the "Old" edge and  MSEdgeDriver for the new/chromium Edge, which is not much help.

**Comment by jhoneill** [comment]
I have a working version. It turns out the failure occurs if you use a V80 or later version of the Microsoft Web driver. The V79 version works with the current V80 build of Edge-Dev. This isn't ideal but is at least a working solution. 

I have made quite a lot of other changes and will send a PR through with some notes on what I have done and leave it to you guys to pick and choose what's worth incorporating. 

@adamdriscoll  I was going to use one of those in a piece on good and not-so-good ways to do parameters, and before publishing that it might be nice to have a quick chat to avoid looking like I'm cricitizing the author rather that saying "Things grow into something like this and if we can do this instead..."

**Comment by jhoneill** [comment]
Just thought I'd share code which works in case anyone else needs it. 

```powershell
Param(
    $BinaryPath = "C:\Program Files (x86)\Microsoft\Edge Dev\Application\msedge.exe",
    [switch]$Headless,
    [switch]$PrivateBrowsing,
    $WebDriverDirectory = "C:\Program Files (x86)\Microsoft\Edge Dev\Application\"
)

$options = New-Object -TypeName OpenQA.Selenium.Chrome.ChromeOptions -Property  @{browserName='' ; BinaryLocation=$BinaryPath}
#Browser name does not need to be set on V79, but does on on V80 or V81.
#The binarypath works on web driver V79 but not 80/81. So put MsEdgeDriver.Exe in the same location as msedge.exe 
#The same applies to the arguments. Work on 79 not on 80/81.  
if($PrivateBrowsing) {$options.AddArguments('InPrivate')}
if($Headless)        {$options.AddArguments('headless')}
$service = [OpenQA.Selenium.Chrome.ChromeDriverService]::CreateDefaultService($WebDriverDirectory, 'msedgedriver.exe')
$driver  = New-Object -TypeName OpenQA.Selenium.Chrome.ChromeDriver  -ArgumentList $service, $options

```
