### ISSUE TITLE
How to handle drop down elements

### ISSUE THREAD

**Issue by JLogan3o13** [adamdriscoll/selenium-powershell#57]
Can you please document a consistent way to handle drop down menus? It is not possible to do a Find-SEElement on a drop down and then use Send-SEKeys, as the field will come back as "not interactable"

In other languages' implementation of Selenium, I can do something like this:

`select = Select(driver.find_element_by_id('UserDropDown'))
 select.select_by_visible_text('Joe_Smith')
`

But I have been unable to get the syntax right in PowerShell. I see a LOT of threads on SO and other sites asking for this kind of info, so a solid example of implementing this would be awesome.

**Comment by the-mentor** [comment]
Hi @JLogan3o13  this is a work in progress function i've been working on give it a spin and let me know if it works for you.

```Function Set-SeSelect {
    Param(
        [OpenQA.Selenium.IWebElement]$Element, 
        [string]$Text,
        [string]$Value
    )

    if($Value){
        $SelectElement = New-Object -TypeName "OpenQA.Selenium.Support.UI.SelectElement" -ArgumentList $Element
        $SelectElement.SelectByValue($Value)
    }
    elseif($Text){
        $SelectElement = New-Object -TypeName "OpenQA.Selenium.Support.UI.SelectElement" -ArgumentList $Element
        $SelectElement.SelectByText($Text)

    }
}```

-DM

**Comment by JLogan3o13** [comment]
Thanks for the response. I have done something similar with Selenium in other languages, and had tried it in PS as well. It does work if the element is actually a select. I know in the particular case I am looking at right now, for example, the element has a tag other than select. So you get the dreaded: "New-Object : Exception calling ".ctor" with "1" argument(s): "Element should have been select but was td"" error. I also get it with dropdowns that are div tags. It may honestly be just malformed html on this page I'm working on. Here is the CSS I am looking at:

<div class="dropdown" id="mainForm-_SupportGroup-Dropdown" style="left: 423px; top: 204px; width: 706px; height: 448.5px; display: none;" xpath="1">
<div class="dropdownContent" style="height: 424.5px; overflow-y: auto;"></div>
<div class="dropdownFooter"></div>
</div>

Once you click on the dropdown, this element is interactable:

<div id="mainForm-_SupportGroupDisplayPaging" style="height:22px;padding-top:2px;" xpath="1"><div class="pagingButton"><a class="firstPage"></a></div><div class="pagingButton"><a class="previousPage"></a></div><input class="textField pagingText watermark" type="text" value="" watermark="1 of 2"><div class="pagingButton"><a class="nextPage"></a></div><div class="pagingButton"><a class="lastPage"></a></div></div>

but not the main element. I did find that if I click on it (manually) I can do something like this:

`  Start-Sleep 10 #give time to manually click dropdown
  $taskDropdown = Find-SeElement -Driver $chrome -Timeout 60 -Id "mainForm-_SupportGroupDisplayPaging"
  Start-Sleep 5
  $hosting = Find-SeElement -Driver $chrome -Timeout 30 -XPath "//div[contains(text(),'Joe_Smith')]"
  $hosting.Click()`

However, if the dropdown is one that dynamically expands content as you scroll down, or worse, has a "next" arrow, even that methodology becomes near useless. 

As I said, could very well just be poorly coded html.

**Comment by itfranck** [comment]
I believe the current version handles that through Get-SeSelectionOption (which act as both a Get and a Set)

V4 (to be released October 4th) will handles Select through : Set-SeSelectValue

Regarding dynamically loading select and other special select, this should be possible to handle it by scrolling into the select box, which is something I am currently working on #122  with the addtion of Actions (Keydown / Key up / mouse move, mouse drag, etc...) 


You can track the progress for that second part on #122 
If you think I missed something, feel free to reopen this ticket.
Thanks.
