### ISSUE TITLE
How to modify timeouts when script is waiting on webpage

### ISSUE THREAD

**Issue by abrikmanis** [adamdriscoll/selenium-powershell#66]
How to modify timeout values when waiting for a response on a webpage?

I'm interacting with a web page that waits for ~2-3min prior to responding to the client.
and In this case, that is expected.

So far I am managing this by wrapping into try block, but this way I'm skipping on other errors as well.
```
$Driver = Start-SeChrome 
Enter-SeUrl https://www.example.com -Driver $Driver
$Element=Find-SeElement -Driver $Driver -Wait -Timeout 10 -name "Button-of-slowness"
try 
{
Invoke-SeClick -Element $Element 
# executes for 2-3 mins
} catch {
#do nothing
}
```

**Comment by itfranck** [comment]
Hey, I see this is open for a while. 
I have took the maintainer role of this repository and 
I plan to have V4 released on the first week of October. 

Amongst the change, the addition of Wait-SeDriver / Wait-SeElement should allow you to achieve what you wish to do simply enough by allowing you to wait for specific conditions before continuing. 
You can see #125 for more details. 



V4
```

Start-SeDriver -Browser Chrome
Set-SeUrl -Url 'https://www.example.com'
$Element = Get-SeElement -By Name -Value "Button-of-slowness"

Send-SeClick -Element $Element 

# If the button get removed from the DOM when the response is received (EG: navigated to another page)
Wait-SeElement -Element $Element -Condition StalenessOf -Timeout 500 

# If you want to wait for a specific component
Wait-SeElement -By Name -Value 'SomeOtherComponenentLoaded' -Timeout 500

```


For the current version, you could wrap something like this 

```

Function Wait-SeElementExists($Driver,$Element,$Timeout) {
    $WebDriverWait = [OpenQA.Selenium.Support.UI.WebDriverWait]::new($Driver, (New-TimeSpan -Seconds $Timeout))
    $SeCondition = [OpenQA.Selenium.Support.UI.ExpectedConditions]::ElementExists($Element)
    try {
        [void]($WebDriverWait.Until($SeCondition))
        return $true
    }
    catch {
        Write-Error $_
        return $false
    }
}
```
(You can take a look at the other conditions that can be used here: https://www.selenium.dev/selenium/docs/api/dotnet/html/Methods_T_OpenQA_Selenium_Support_UI_ExpectedConditions.htm)
