### ISSUE TITLE
Send Blank keys via Send-SeKeys

### ISSUE THREAD

**Issue by adamdriscoll** [adamdriscoll/selenium-powershell#67]
We have tests in UD that send empty strings to SendKeys.

```
Send-SeKeys -Element $Element -Keys ''
```

This doesn't work because the value is mandatory for keys. Probably should just remove the mandatory and send an empty string when you do that. This is valid for selenium.

**Comment by jhoneill** [comment]
best way might be to just have allow null or empty.

**Comment by vexx32** [comment]
Pretty sure there's an `[AllowEmpty]` attribute or something somewhere in the PS libraries...
