### ISSUE TITLE
Import-Module isn't exporting classes

### ISSUE THREAD

**Issue by adamdriscoll** [adamdriscoll/selenium-powershell#69]
There are attributes used for certain cmdlets that throw exceptions when imported by Import-Module in PowerShell v5.1 

Version: v3-beta1

**Comment by lhoff** [comment]
> There are attributes used for certain cmdlets that throw exceptions when imported by Import-Module in PowerShell v5.1
> 
> Version: v3-beta1

Would that be the cause of this error?

Thanks!

```
Cannot find the type for custom attribute 'ValidateURIAttribute'. Make sure that the assembly that contains this
type is loaded.
At C:\Users\User\selenium-powershell\Selenium.psm1:337 char:9
+         [ValidateURIAttribute()]
+         ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ([ValidateURIAttribute()]:AttributeAst) [], RuntimeException
    + FullyQualifiedErrorId : CustomAttributeTypeNotFound
```

**Comment by adamdriscoll** [comment]
Yep. This is how I'm working around it right now. 

https://github.com/ironmansoftware/universal-dashboard/blob/master/src/Selenium/Selenium.ps1#L21

**Comment by lhoff** [comment]
Sorry, that doesn't work for me:

```
Install-Module : A parameter cannot be found that matches parameter name 'AllowPrerelease'.
At C:\Users\User\selenium-powershell\BugWorkaround.ps1:4 char:29
+     Install-Module Selenium -AllowPrerelease -Force -Scope CurrentUse ...
+                             ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Install-Module], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Install-Module
```
And the following is thrown whether or not I include AllowPrerelease:

```
At C:\Users\User\selenium-powershell\SeleniumClasses.ps1:13 char:32
+ ...     if ($arguments -isnot [OpenQA.Selenium.Remote.RemoteWebDriver]) {
+                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unable to find type [OpenQA.Selenium.Remote.RemoteWebDriver].
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : TypeNotFound
```

$PSVersionTable
```
Name                           Value
----                           -----
PSVersion                      5.1.17134.858
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.858
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by jhoneill** [comment]
@lhoff  did you ever find a resolution to this ? If you import the psm1 file instead of the PSD1 file you will get missing class errors.

**Comment by vexx32** [comment]
@adamdriscoll typically what I'd recommend doing here is just double up on your attribute class. The PowerShell class resolver is a bit janky across the module boundary, and I've found I often need to define a `TypeName` class as well as a `TypeNameAttribute` class (usually I'll just implement one and then have the other inherit it with no changes, behaving a bit like an alias).

```ps1
class MyClassAttribute : ValidateEnumeratedArgumentsAttribute {
    $Property = 1
}

class MyClass : MyClassAttribute { }
```

**Comment by adamdriscoll** [comment]
@vexx32 - Thank you for this info! I haven't taken the time to solve this but I'm going to play with this today and see if I can avoid this issue. I'm seeing it in UD all the time now.

**Comment by adamdriscoll** [comment]
This did the trick. Seems to work for me in PSv5.1 and PSv7
