### ISSUE TITLE
[request] add moveToElement function

### ISSUE THREAD

**Issue by franklin050187** [adamdriscoll/selenium-powershell#72]
Hello,

Would it be possible to add movetoelemnt function in order to deal with mouseover menus ?

found this but my skill in PS and CS are not able to convert it to a proper function :
https://github.com/apetrovskiy/STUPS/blob/7a2bfbc6876eaa47d0de4d2753220e189bcbe799/SePSX/SePSX/Commands/Actions/MoveSeCursorToWebElementCommand.cs

btw great worl, love the modul and how easy it is to use

**Comment by itfranck** [comment]
I'm starting the work on this now. 
I will close this specific request, but this will be implemented as part of #122 ticket, which is to add not only MoveToElement but all other interactions (Drag & drop, scroll, key down / key up, etc...) 

ETA is October 4th for the release of V4, which will include this change.
