### ISSUE TITLE
Timeout issue with Examples function

### ISSUE THREAD

**Issue by Antexa** [adamdriscoll/selenium-powershell#73]
I try to run the exemple, no chance from now .

```
c:\Users\Desktop\selenium-powershell-master\Examples\A-Simple-Google-Search.ps1
1585323599580   mozrunner::runner       INFO    Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\\AppData\\Local\\Temp\\rust_mozprofilen8Oa6h"
Exception lors de l'appel de « Until » avec « 1 » argument(s) : « Timed out after 2 seconds »
Au caractère C:\Users\Desktop\selenium-powershell-master\Selenium.psm1:756 : 13
+             $WebDriverWait.Until($Condition)
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebDriverTimeoutException
```

Also could you please explain me how to run the StartSeChrome cmdlet with the latest chromedriver ?

**Comment by itfranck** [comment]
@Antexa I can't help much for the old version as I didn't really use it but with V4 (in pre-release), the example should work properly. 

To start the driver
```
#Chrome 
Start-SeDriver -Browser Chrome -StartURL 'google.com/ncr'
#Firefox 
Start-SeDriver -Browser Firefox -StartURL 'google.com/ncr'
```
If you want to use a driver more recent than what is included, you will need to download it and specify its location through `-WebDriverPath` parameter. 


Here's the Google example reduced to the minimum amount of lines 
```
Start-SeDriver -Browser Chrome -StartURL 'google.com/ncr'
$Searchbox = Get-SeElement -By Name -value q -Single
Invoke-SeKeys -Element $Searchbox -Keys 'Powershell-Selenium'
Invoke-SeKeys -Element $Searchbox -Keys ([OpenQA.Selenium.Keys]::Enter) -Sleep 2
$LogoImageElement = Get-SeElement -By TagName -Value img -Timeout 10 -Filter {$_.Attributes.src -like '*/logos/*'}
Invoke-SeClick  -Element $LogoImageElement
Stop-SeDriver 
```

Note that there is documentation now in the Docs folder on each cmdlet which can provide some additional insights.

Also note: For chrome, you can download the latest Driver using: `Update-SeDriver -Browser Chrome`
Other drivers are not implemented yet

If you have trouble with timeouts, you can add specific `-Sleep` on the cmdlet prior to the timeout or use `Wait-SeElement` / `Wait-SeDriver`. 


I am also re-working the `Get-SeElement` so the default way to get elements is more robust and wait for the elements to be loaded by using a different wait until condition behind the curtain before returning (#193)

Feel free to reopen if you still have issues with this using V4 prerelease.
