### ISSUE TITLE
Custom Attribute Not Found ValidateURIAttribute - current master version

### ISSUE THREAD

**Issue by PhelixPhoenix** [adamdriscoll/selenium-powershell#76]
I hit this when assigning the driver like this: $Driver = Start-SeEdge
This happens for every browser.

Cannot find the type for custom attribute 'ValidateURIAttribute'. Make sure that the assembly that contains this type is loaded.
At C:\Users\user\Desktop\script\selenium-powershell-master\Selenium.psm1:343 char:9
+         [ValidateURIAttribute()]
+         ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ([ValidateURIAttribute()]:AttributeAst) [], RuntimeException
    + FullyQualifiedErrorId : CustomAttributeTypeNotFound

**Comment by itfranck** [comment]
Closing for the same reason as #77 . If  you still have issues, please reopen #77 and confirm how you import the module there. Thanks.
