### ISSUE TITLE
Custom Attribute 'ValidateIsWebDriverAttribute' not found

### ISSUE THREAD

**Issue by PhelixPhoenix** [adamdriscoll/selenium-powershell#77]
This happens when trying to add the site url for the browser to open like this: Enter-SeUrl "https://site.com"

Cannot find the type for custom attribute 'ValidateURIAttribute'. Make sure that the assembly that contains this type is loaded.
At C:\Users\user\Desktop\script\selenium-powershell-master\Selenium.psm1:343 char:9
+         [ValidateURIAttribute()]
+         ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ([ValidateURIAttribute()]:AttributeAst) [], RuntimeException
    + FullyQualifiedErrorId : CustomAttributeTypeNotFound
 
Cannot find the type for custom attribute 'ValidateIsWebDriverAttribute'. Make sure that the assembly that contains this type is loaded.
At C:\Users\user\Desktop\script\selenium-powershell-master\Selenium.psm1:588 char:9
+         [ValidateIsWebDriverAttribute()]
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ([ValidateIsWebDriverAttribute()]:AttributeAst) [], RuntimeException
    + FullyQualifiedErrorId : CustomAttributeTypeNotFound

**Comment by jhoneill** [comment]
Did you load the module by specifying the PSM1 file or the PSD1 file. Currently there is an issue with the way the classes are loaded. I'm putting together a fix but right now it will fail if you by-pass the PSD1

**Comment by itfranck** [comment]
Indeed, module should always be loaded either by name or through the PSD1. 

@PhelixPhoenix 

There are additional stuff in the PSD1 regarding the additional script to process, required assemblies, etc... 

If this was loaded this way, please confirm the OS, module version used, PS version used and, if this does not occurs in all scenarios, reproducible code example.

**Comment by itfranck** [comment]
Closing this issue as it is inactive. 
I also believe it was properly answered.
If loading the module by name or by psd1 (if you need to specify the path) do not work, feel free to reopen this ticket and provide relevant details such as : 

Which OS ?
Which Powershell Version ?
How specifically do you import the module (paste the import statement)  ?

Also, add the `-Verbose` flag to your Import-Module and paste the content here so we can take a look.
