### ISSUE TITLE
Startpage Wrong command

### ISSUE THREAD

**Issue by Schwanowski** [adamdriscoll/selenium-powershell#78]
Hi there,

on the startpage https://github.com/adamdriscoll/selenium-powershell the advice is to install the module manually via:

Import-Module "{FullPath}\selenium-powershell\Selenium.psm1"

for my research, this is not corrent (and doesnt work), while

Import-Module "{FullPath}\selenium-powershell\Selenium.psd1" 

seems to work.

Am I right?

Thanks,

Alex

**Comment by adamdriscoll** [comment]
That is correct. Thanks!
