### ISSUE TITLE
Integration/Ability to run projects created from the Selenium IDE? 

### ISSUE THREAD

**Issue by s0nders** [adamdriscoll/selenium-powershell#84]
Love the project so far, is there any plans to add the ability to run projects created from the IDE? 

Thanks!

**Comment by itfranck** [comment]
This look interesting.

It seems like it would be super easy to get started and the command could provide the PS equivalent for more flexibility so you could record something very fast, get the PS selenium equivalent and add new stuff in-between (or just execute "as is") 

I am working on getting a V4 ready (target is first week of September) but that's something I will definitely start looking at right after.

**Comment by ili101** [comment]
I have some old code I used that takes the browser extension C# output and convert it to PowerShell code.
I see there is now a ".side" json file that is probably easier to convert.

**Comment by bjornwahman** [comment]
This would be a great feature :)

**Comment by ili101** [comment]
I created a function to implement this.
It only support some of the commands for now
You can check it out and give some feedback if you like (It's only compatible with V4)

**Comment by itfranck** [comment]
Closing this as it was implemented starting at V4.0.0-preview1
