### ISSUE TITLE
CORS and CORS handling with Selenium

### ISSUE THREAD

**Issue by tikesavage** [adamdriscoll/selenium-powershell#85]
alot of third party sites are returning CORS policy: No Access-Control-Allow-Origin' header is present on the requested resource.
is there a cmdlet to turn of chromes -disable-web-security setting to get around this? or am i going about this wrong?
specifically i am trying to sign into fedex website for user creation automation. no they dont have an api for this already.

**Comment by tikesavage** [comment]
Access to XMLHttpRequest at 'https://api.fedex.com/user/v2/login/validate' from origin 'https://www.fedex.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
jquery.min.1494c0abbe501301e2ab9daecc6082a8.js:202 POST https://api.fedex.com/user/v2/login/validate net::ERR_FAILED

**Comment by itfranck** [comment]
@tikesavage You can start Chrome with the desired command line arguments using the `-Arguments` parameter. 

```
Start-SeChrome -Arguments '--disable-web-security'
```
