### ISSUE TITLE
Error when running with Powershell on Raspberry Pi 

### ISSUE THREAD

**Issue by matt199x** [adamdriscoll/selenium-powershell#87]
I am getting the following error when trying to run start-sechrome  on my Raspberry Pi with Raspbian. It works fine for me in Ubuntu and OSX with powershell. Similar error when trying to use Firefox. 

```
PS /home/pi> start-sechrome
New-Object: /home/pi/.local/share/powershell/Modules/Selenium/3.0.0/Selenium.psm1:252
Line |
 252 |  …   $Driver = New-Object -TypeName "OpenQA.Selenium.Chrome.ChromeDriver …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling ".ctor" with "2" argument(s): "Exec format error"

WARNING: Web driver was not created`
```

**Comment by the-mentor** [comment]
This happens because there is no arm64 drivers for the various drivers.
This is a problem upstream that unfortunately we can't fix until they release it for arm platforms like the raspberry pi.

-DM

**Comment by adamdriscoll** [comment]
Seems like we close this for now and if they ever release support for this in the future we can reopen.
