### ISSUE TITLE
How to make it work in MacOS

### ISSUE THREAD

**Issue by mkellerman** [adamdriscoll/selenium-powershell#9]
Awesome work!

Is there a way to make this work on MacOS?
````
New-Object : Exception calling ".ctor" with "0" argument(s): "The chromedriver file does not exist in the current directory or in a directory on the PATH environment variable. The driver can be downloaded at http://chromedriver.storage.googleapis.com/index.html."
At /Users/mkellerman/.local/share/powershell/Modules/Selenium/1.1/Selenium.psm1:4 char:5
+     New-Object -TypeName "OpenQA.Selenium.Chrome.ChromeDriver"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
+ FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand

You cannot call a method on a null-valued expression.
At /Users/mkellerman/.local/share/powershell/Modules/Selenium/1.1/Selenium.psm1:34 char:5
+     $Driver.Navigate().GoToUrl($Url)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : InvokeMethodOnNull
````

**Comment by adgaines** [comment]
I made it work on Ubuntu which should be similar for MacOS.

**Step 1: Install the latest version**
As of this writing, you will need the beta version, "1.3.0". In a PowerShell terminal, type the following:

`Update-Module Selenium -AllowPrerelease`

**Step 2: Fix the permission problem on the module's binaries** 

1. Open a terminal window
2. Navigate to the location where the PowerShell modules are installed for your system. For this example, let's assume the module was installed at "~/.local/share/powershell/Modules/Selenium/1.3.0/".
`cd ~/.local/share/powershell/Modules/Selenium/1.3.0/`
3. Execute the following command to add the "Execute" permission
For Mac OS:
`chmod +x assemblies/macos/chromedriver`
`chmod +x assemblies/macos/geckodriver`
For Linux:
`chmod +x assemblies/linux/chromedriver`
`chmod +x assemblies/linux/geckodriver`

That's it!! .. or at least that is all it took for me running on Ubuntu. I haven't tested on MacOS but it should have the same result.

I didn't have time to try to do a pull request to help the maintainers but at least this may help the next person tripping over the same problem. For the maintainers, Good luck overcoming the permissions problem. I am sure i am not the only one looking forward to the next commit version that does not require the above hack.

**Comment by the-mentor** [comment]
@mkellerman MacOS should work I know I added and tested it.
The only issue we have at the moment with Linux and MacOS is when installing from PSGallery the execution permissions do not transfer to UNIX.
So you will have to run chmod +x on the Macos assemblies.
`chmod +x assemblies/macos/chromedriver
chmod +x assemblies/macos/geckodriver`

Let me know if you need further assistance.
