### ISSUE TITLE
Request - Get-SeLocation

### ISSUE THREAD

**Issue by vexx32** [adamdriscoll/selenium-powershell#92]
Currently if we want to check the current location/url of the running driver, we have to grab the driver object itself and check the `.Url` property.

Would be nice to abstract that out to a simple `Get-SeLocation` / `Get-SeUrl` function so that we don't need to think about it, especially when we've started a driver with `-AsDefaultDriver`. 🙂

**Comment by itfranck** [comment]
Never better served than by ourselves :)
