### ISSUE TITLE
-AsDefaultDriver functionality

### ISSUE THREAD

**Issue by vexx32** [adamdriscoll/selenium-powershell#93]
Currently the Selenium module stores the driver object in the `$global:` space when you start a driver with `-AsDefaultDriver`, which seems a bit unwise, to me at least.

I'd be inclined to say it would be better to store it in the module scope (aka `$script:` scope) and then provide users with a `Get-SeDriver` function to retrieve the current default driver if they have a transient need for it later.

Naturally some of this is made easier in that we _can_ just store the driver objects initially, but in complex Pester scripts it sometimes requires jumping through a few hoops to keep that variable easily accessible, and it's also quite repetitive to keep referencing the driver directly.

`-AsDefaultDriver` is really nice, but it'd be good to have a bit nicer interface with the less-accessible driver when it's needed, preferably without putting anything directly in the global scope. 🙂

**Comment by itfranck** [comment]
I was thinking around the following lines for V4. 


- Start-SeDriver (#101 ) / Stop-SeDriver will add / remove a driver to the "stack"
- Get-SeDriver will return the "current" driver
- If a cmdlet does not specify a `-target` parameter, the last driver started will be considered as the default (or "current")

About Start-SeDriver (related to this specific item)
- Start-SeDriver is to have an optional Name parameter 
- It will use a Browser parameter to expose the different driver available 


Some examples
```
# For it to work, you'd have to use the Name parameter on Start-SeDriver too
Get-SeDriver -Name 'ChromeV83' # Would return the driver instance named ChromeV83

# By browser type, leveraging same argument completion than Start-SeDriver
Get-SeDriver -Browser Chrome  # Would return all Chrome Drivers currently active


# Return current driver
Get-SeDriver 

# Return a list of all active drivers
Get-SeDriver -All 

# Return a list of currently active Chrome browser
Get-SeDriver -Browser Chrome 

# Return the browser named MyChromeInstance defined in Start-SeDriver -Name 'MyChromeInstance' -Browser Chrome ...
Get-SeDriver -Name 'MyChromeInstance'


# Stop current driver
Get-SeDriver | Stop-SeDriver

# Stop all active drivers
Get-SeDriver -All | Stop-SeDriver
```

The only thing I have been juggling through in my head as I was typing this is: 
Should Get-SeDriver return the current driver or all drivers. 
(Even though I wrote my example this way, I am thinking it would make more sense to return all drivers and allow filtering down by name / browser type) 


To accompany all of this, a companion `Select-SeDriver` would allow to change the current driver to another one.

**Comment by vexx32** [comment]
I think that makes sense, a fairly good solution. 👍
