### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by gonaumov** [adamdriscoll/selenium-powershell#94]
Hello. 

I am sorry. Maybe I am not asking that question on the proper place. 
How I can get a some kind of collection of elements? Something like:
`document.querySelectorAll("#some-id tag.class-name")`

Best regards

**Comment by Spiker985** [comment]
I recommend taking a look at [this](https://www.w3schools.com/cssref/css_selectors.asp), as well as investigating an online resource for CSS Selectors

**Comment by gonaumov** [comment]
@Spiker985 Thank you for the answer but I am used to write CSS selectors. My question was how to get collection from more than one element with selenium-powershell. Unfortunately I cannot find similar example.

**Comment by Spiker985** [comment]
@gonaumov You could always create your own collection to loop through either with `$array = New-Object -TypeName System.Collections.ArrayList` or simply with `$array = @()`

The first option is the .NET way, and is slightly faster. The second way is the pure PowerShell way and will work on any machine with PowerShell.

**Comment by itfranck** [comment]
@gonaumov 

`Get-SeElement` already return a collection of all the matching elements.
It uses the [WebDriver FindElements](https://www.selenium.dev/selenium/docs/api/dotnet/html/M_OpenQA_Selenium_ISearchContext_FindElements.htm) method behind the curtain.
```
Start-SeChrome -StartURL 'https://www.google.ca' -AsDefaultDriver
$Elements = Get-SeElement -By CssSelector -Selection 'div'
```

Does that answer your question or else can you provide a reproducible example to `Get-SeElement` where you'd expect a collection and get a single result ?

**Comment by itfranck** [comment]
I will mark this as closed but don't hesitate to reopen it if it didn't answer your question.
Thanks.
