### ISSUE TITLE
Remove the many aliases for everything.

### ISSUE THREAD

**Issue by itfranck** [adamdriscoll/selenium-powershell#99]
There's so many aliases in the module.
It might seems like it is convenient at first, but it create a situation where you can write the same thing in many different ways

Let's take for example `Get-SeElement`

`Get-SeElement -By Name -Selection 'loginfmt'`

Now, all the lines below are valid way to call the same statement. 

**Selection alias**
```
#All aliases for selection
#[Alias("CssSelector", "Name", "Id", "ClassName", "LinkText", "PartialLinkText", "TagName", "XPath")]
Get-SeElement -By Name -name 'loginfmt'
Get-SeElement -By Name -CssSelector 'loginfmt'
Get-SeElement -By Name -LinkText 'loginfmt'
```

**Target alias**
```
  #[Alias('Element', 'Driver')]
Get-SeElement -By Name -Selection 'loginfmt' -Target $Driver 
Get-SeElement -By Name -Selection 'loginfmt' -Element $Driver 
Get-SeElement -By Name -Selection 'loginfmt' -Driver $Driver 
```

**Function aliases**
```
Find-SeElement  -By Name -Selection 'loginfmt' -Driver $Driver 
SeElement  -By Name -Selection 'loginfmt' -Driver $Driver 
```

Ultimately, all these are valid way to get to the same thing.
Now let's combine theses

```
Seelement -Name 'loginfmt' -Element $Driver
#Or 
Seelement -By name -xpath 'loginfmt' -Element $Driver
```

I think all theses aliases bring more confusion than they bring ease of use.

**Comment by vexx32** [comment]
Agreed. Part of this looks like it was introduced to retain some semblance of compatibility, but just like I noted in #74, it's significantly more confusing than it is really helpful.
